global:
  scrape_interval: 10s
  evaluation_interval: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["store-alertmanager:9093"]

rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: store-api
    metrics_path: /metrics
    static_configs:
      - targets: ["store-api:5000"]

  - job_name: store-db
    static_configs:
      - targets: ["store-postgres-exporter:9187"]
